name: XML Syntax

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  syntax_xml:
    name: XML Syntax
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get last successful commit
        id: last-successful-commit
        uses: SamhammerAG/last-successful-build-action@v7
        with:
          branch: main
          workflow: ${{ github.workflow }}
          verify: true

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          base_sha: ${{ steps.last-successful-commit.outputs.sha }}
          files: |
            **/*.xml

      - name: Update APT repositories
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: "sudo apt update"

      - name: Install xmllint
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: "sudo apt-get -y install libxml2-utils"

      - name: Check changed files
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          set +e
          ERROR=0
          for FILE in ${{ steps.changed-files.outputs.all_changed_files }}; do
              MESSAGE=$(xmllint --noout "$FILE" 2>&1)
              if [ $? -ne 0 ]; then
                  ERROR=255
                  LINE=$(echo "$MESSAGE" | head -n 1 | cut -d":" -f 2)
                  echo "::error file=$FILE,line=$LINE::$MESSAGE"
              fi
          done
          exit $ERROR
